ALTER TABLE device ADD COLUMN IF NOT EXISTS device_value DOUBLE;

ALTER TABLE device ADD COLUMN IF NOT EXISTS location VARCHAR(100);

ALTER TABLE device ADD COLUMN IF NOT EXISTS last_online_time TIMESTAMP;

ALTER TABLE device ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE emergency_call ADD COLUMN IF NOT EXISTS response_time TIMESTAMP;

ALTER TABLE emergency_call ADD COLUMN IF NOT EXISTS resolved_time TIMESTAMP;